package com.bitranger.example.dao;

import java.util.List;

import com.bitranger.example.model.Book;

/**
 * Definition of
 * Data Access Object for model.Book
 * 
 * @see impl.DAOBook
 * @author BowenCai
 *
 */
public interface IDAOBook {

	/**
	 * 
	 * @param id
	 * @return book of this id
	 */
	Book 			getById(int id);
	
	/**
	 * 
	 * @return all books in DB
	 */
	List<Book> 		getAll();
	
	/**
	 * save book
	 * @param book
	 * @return id generated by DB
	 */
	int				save(Book book);
	
	/**
	 *  update this book
	 * @param book
	 */
	void			update(Book book);
	
	/**
	 * delete book of this id
	 * @param id
	 */
	void			delete(Book book);
	
	/**
	 * batch delete by id
	 * @param bookList
	 */
	void 			delete(List<Book> bookList);
}




